name: Deploy proto files to typescript and golang

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  deploy:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/setup-qemu-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          
      - name: Build Docker image
        run: |
          docker build -t maxischmaxi/jstreams-gen --build-arg GH_TOKEN=${{ secrets.GH_TOKEN }} --build-arg GH_SHA=$GITHUB_SHA .
          docker run maxischmaxi/jstreams-gen
